export const ACTION_TYPES = {
  SET_ALL_OF_COMPANIES: "SET_ALL_OF_COMPANIES",
  SET_ALL_OF_PRODUCTS: "SET_ALL_OF_PRODUCTS",
  SELECT_CATEGORY: "SELECT_CATEGORY",
  FILTER_PRODUCTS_BY_BRAND: "FILTER_PRODUCTS_BY_BRAND",
  FILTER_PRODUCTS_BY_TAG: "FILTER_PRODUCTS_BY_TAG",
  SORTING_PRODUCTS: "SORTING_PRODUCTS",
  ADD_PRODUCT_TO_BASKET: "ADD_PRODUCT_TO_BASKET",
  INCREASE_PRODUCT_AMOUNT: "INCREASE_PRODUCT_AMOUNT",
  DECREASE_PRODUCT_AMOUNT: "DECREASE_PRODUCT_AMOUNT",
};
